version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_AI_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sales_analysis
      - S3_BUCKET_NAME=sales-analysis-files
      - S3_REGION=us-east-1
      - AI_SERVICE_URL=http://ai-agent:8000

  ai-agent:
    build: ./ai-agent
    ports:
      - "8000:8000"
    volumes:
      - ./ai-agent:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - S3_BUCKET_NAME=sales-analysis-files
      - S3_REGION=us-east-1
      - MONGODB_URI=mongodb://mongodb:27017/sales_analysis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: